// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTracker;

#nullable disable

namespace MovieTracker.Migrations
{
    [DbContext(typeof(MovieTrackerContext))]
    [Migration("20220604232743_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MovieTracker.Models.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Score")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("MovieTracker.Models.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Score")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Watched")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("MovieTracker.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Score")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Watched")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieTracker.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Score")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MovieTracker.Models.RoleActor", b =>
                {
                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActorId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleActor");
                });

            modelBuilder.Entity("MovieTracker.Models.RoleEpisode", b =>
                {
                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EpisodeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleEpisode");
                });

            modelBuilder.Entity("MovieTracker.Models.RoleMovie", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleMovie");
                });

            modelBuilder.Entity("MovieTracker.Models.RoleSeries", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SeriesId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleSeries");
                });

            modelBuilder.Entity("MovieTracker.Models.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Score")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Watched")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("MovieTracker.Models.SeriesEpisode", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SeriesId", "EpisodeId");

                    b.HasIndex("EpisodeId")
                        .IsUnique();

                    b.ToTable("SeriesEpisode");
                });

            modelBuilder.Entity("MovieTracker.Models.RoleActor", b =>
                {
                    b.HasOne("MovieTracker.Models.Actor", "Actor")
                        .WithMany("RoleActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTracker.Models.Role", "Role")
                        .WithMany("RoleActors")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MovieTracker.Models.RoleEpisode", b =>
                {
                    b.HasOne("MovieTracker.Models.Episode", "Episode")
                        .WithMany("RoleEpisodes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTracker.Models.Role", "Role")
                        .WithMany("RoleEpisodes")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MovieTracker.Models.RoleMovie", b =>
                {
                    b.HasOne("MovieTracker.Models.Movie", "Movie")
                        .WithMany("RoleMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTracker.Models.Role", "Role")
                        .WithMany("RoleMovies")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MovieTracker.Models.RoleSeries", b =>
                {
                    b.HasOne("MovieTracker.Models.Role", "Role")
                        .WithMany("RoleSeries")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTracker.Models.Series", "Series")
                        .WithMany("RoleSeries")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MovieTracker.Models.SeriesEpisode", b =>
                {
                    b.HasOne("MovieTracker.Models.Episode", "Episode")
                        .WithOne("SeriesEpisode")
                        .HasForeignKey("MovieTracker.Models.SeriesEpisode", "EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTracker.Models.Series", "Series")
                        .WithMany("SeriesEpisodes")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MovieTracker.Models.Actor", b =>
                {
                    b.Navigation("RoleActors");
                });

            modelBuilder.Entity("MovieTracker.Models.Episode", b =>
                {
                    b.Navigation("RoleEpisodes");

                    b.Navigation("SeriesEpisode")
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTracker.Models.Movie", b =>
                {
                    b.Navigation("RoleMovies");
                });

            modelBuilder.Entity("MovieTracker.Models.Role", b =>
                {
                    b.Navigation("RoleActors");

                    b.Navigation("RoleEpisodes");

                    b.Navigation("RoleMovies");

                    b.Navigation("RoleSeries");
                });

            modelBuilder.Entity("MovieTracker.Models.Series", b =>
                {
                    b.Navigation("RoleSeries");

                    b.Navigation("SeriesEpisodes");
                });
#pragma warning restore 612, 618
        }
    }
}
